twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
        paths:
        '%kernel.project_dir%/templates': templates
        form_themes:
         'bootstrap_5_layout.html.twig'
        default_locale: 'fr'
